postgres:
  hostname: postgres
  image: postgres:9.4.5
  environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=user
  ports:
    - 5432:5432
  security_opt:
    - label:user:user
    - label:role:user
