version: 2
jobs:
  build:
    working_directory: /numbers
    docker:
      - image: stabenfeldt/ubuntu-w-docker-compose:1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . -t $DOCKER_HUB_USER_ID/$PROJECT_NAME
      - run: docker run -e JWT_SECRET_KEY='xx' --entrypoint bundle $DOCKER_HUB_USER_ID/$PROJECT_NAME exec rails test

      - deploy:
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

            docker tag $DOCKER_HUB_USER_ID/$PROJECT_NAME $DOCKER_HUB_USER_ID/$PROJECT_NAME:$CIRCLE_SHA1
            docker tag $DOCKER_HUB_USER_ID/$PROJECT_NAME $DOCKER_HUB_USER_ID/$PROJECT_NAME:latest

            docker push $DOCKER_HUB_USER_ID/$PROJECT_NAME:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/$PROJECT_NAME:latest
